export { ReactComponent as BackIcon } from './icons/back.svg'
export { ReactComponent as LikeIcon } from './icons/like.svg'
export { default as quality } from './icons/quality.svg?url'
export { ReactComponent as StarIcon } from './icons/star.svg'
export { ReactComponent as TrashIcon } from './icons/trash.svg'
export { default as truck } from './icons/truck.svg?url'

export { default as instagram } from './images/instagram.svg?url'
export { default as telegram } from './images/telegram.svg?url'
export { default as viber } from './images/viber.svg?url'
export { default as vk } from './images/vk.svg?url'
export { default as whatsapp } from './images/whatsapp.svg?url'
export { default as logo } from './images/logo.svg?url'
